### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by xiaoyu1004** [jbush001/NyuziToolchain#109] opened 2022-12-03 05:40 UTC
![screenshot-20221203-133752](https://user-images.githubusercontent.com/80047235/205426104-3d24b85b-e219-4d0d-adfb-f429eb6d9521.png)
command: cmake .. -G ninja

**Comment by jbush001** [comment] 2022-12-03 15:56
duplicate of #204

**Closed by jbush001** 2022-12-03 15:56 UTC
